APP_VERSION=dev
PROJECT_NAME=Java Secure Properties App
PROJECT_DESCRIPTION=Interface pour chiffrer/dechiffrer des valeurs via MuleSoft Secure Properties Tool.
PROJECT_AUTHOR=David CHOCHO
PROJECT_SOURCE_URL=https://github.com/Davosthecool/java-secure-properties-app